<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    
    <xacro:property name="base_mass" value="5.0" />
    <xacro:property name="wheel_mass" value="1.0" />



    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />

    </link>
    
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" 
                                 o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />        
        </link>
    </xacro:macro>    

    <xacro:wheel_link prefix="right_rear" />
    <xacro:wheel_link prefix="left_rear" />
    <xacro:wheel_link prefix="right_front" />
    <xacro:wheel_link prefix="left_front" />


    <joint name="footprint_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>   

    <xacro:macro name="wheel_joint" params="prefix a b">
        <joint name="base_${prefix}_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <origin xyz="${a * base_length / 4.0} ${b * (base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>    

    <xacro:wheel_joint prefix="right_rear" a="-1" b="-1" />
    <xacro:wheel_joint prefix="left_rear" a="-1" b="1"/>
    <xacro:wheel_joint prefix="right_front" a="1" b="-1"/>
    <xacro:wheel_joint prefix="left_front" a="1" b="1"/>

</robot>